In [38]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

    def forward(self, x):
        x = nn.Dropout(p=0.1,inplace=True)(x)
        return x

net = Net()                                                             


net(a)                                                                  
# tensor([0., 0., 0., 2., 2., 2., 0., 0., 2., 2.]) 

# net.eval()

# net(a)
# tensor([0., 0., 0., 2., 2., 2., 0., 0., 2., 2.])
a


tensor([1.1111, 1.1111, 0.0000, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111,
        1.1111])

In [53]:
net.eval()
a = torch.ones(10)                                                     

# net(a)
print(a)
with torch.no_grad():
    print(net(a))
# net(a)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111,
        1.1111])


In [11]:
a

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
class model(nn.Module):
    def __init__(self, pool_size=(4, 4)):
        super(Test, self).__init__()
       
        self.layer = nn.Linear(1, 1, bias=False)
        self.dropout = nn.Dropout()
   
    def forward(self, x):
        out = self.dropout(self.layer(x))
        return out

model.train()
x = 0
for i in range(10):
    print(model(x))

TypeError: Module.train() missing 1 required positional argument: 'self'